language: csharp
mono: none
dotnet: 3.1.100
os: linux
dist: xenial
env:
  global:
    - PROJECT_NAME="Sylver.Network"

script:
  - dotnet restore
  - dotnet build ./src/$PROJECT_NAME/$PROJECT_NAME.csproj -c Release
  - dotnet test ./test/$PROJECT_NAME.Tests/$PROJECT_NAME.Tests.csproj -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Sylver.Network.Tests*]*" /p:Exclude="[xunit*]*"

after_script:
  - bash <(curl -s https://codecov.io/bash)