trigger:
  branches:
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'

- script: dotnet build --configuration Release
  displayName: 'Build'
- script: dotnet test
  displayName: 'Test'
