trigger:
  branches:
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    dotnet build --configuration Release
  displayName: 'Build'

- script: |
    dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"
  displayName: 'Test'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Uploading coverage'
