name: LiteNetwork Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library
      run: dotnet build --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

  build-samples:
    runs-on: ubuntu-latest
    needs: build-library
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
          7.0.x

    - name: Build samples
      run: |
        dotnet build samples/echo/LiteNetwork.Sample.Echo.sln -c Release
        dotnet build samples/hosting/LiteNetwork.Sample.Hosting.sln -c Release
        dotnet build samples/custom-packet-reader-writer/LiteNetwork.Sample.CustomPacketReaderWriter.sln -c Release
